server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: ms-users
  datasource:
    url: ${DB_USERS_URL:jdbc:postgresql://pg-26c06432-cesarmaldonadomecanicodae13-b1f5.a.aivencloud.com:20436/defaultdb?sslmode=require}
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_pYbx3ZFApq7AA_T_Qyh}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
