services:
  bff-usuarios:
    build: .
    container_name: fit-bff-usuarios
    restart: unless-stopped
    environment:
      MS_USERS_URL: ${MS_USERS_URL:-http://fit-users-service:8090}
      JWT_SECRET: ${JWT_SECRET:-fitproject-secret-key-must-be-at-least-32-chars-long}
      JWT_EXPIRATION: ${JWT_EXPIRATION:-86400000}
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - fit-network

networks:
  fit-network:
    external: true
